version: '3'
services:
   database:
       image: postgis/postgis
       container_name: postgis 
       ports:
                 - "54320:5432"
       environment:
              - POSTGRES_USER=sia_admin
              - POSTGRES_PASSWORD=SIADB1004**
              - POSTGRES_MULTIPLE_DATABASES=sia_backend
              - POSTGRES_INITDB_ARGS=--encoding=UTF-8
              - ALLOW_IP_RANGE=0.0.0.0/0
       volumes:
              - "./pgdata:/var/lib/postgres/data"
              - "./create-database.sh:/docker-entrypoint-initdb.d/create-database.sh"
              - "./schemas:/docker-entrypoint-initdb.d/schemas"

   app:
     image: alstp123/sia_backend:latest
     container_name: sia_app
     ports:
              - "8082:8082"
     build:
       context: .
     command:
       - bash
       - -c
       - |
         /wait-for-it.sh database:5432 -t 20
     depends_on:
       - database
     environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/sia_backend
      - SPRING_DATASOURCE_USERNAME=sia_backend
      - SPRING_DATASOURCE_PASSWORD=SIADB1004**
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



